version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: speedrun-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=speedrun-project-manager
    volumes:
      - mongodb_data:/data/db
    networks:
      - speedrun-network

  mongo-express:
    image: mongo-express:1.0.2
    container_name: speedrun-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin123
    depends_on:
      - mongodb
    networks:
      - speedrun-network

volumes:
  mongodb_data:

networks:
  speedrun-network:
    driver: bridge
